#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPDEFINES=["GDEXTENSION", "MPACK_EXTENSIONS"])
env.Append(CPPPATH=[".", "mpack/src"])

addon_sources = [
    "register_types.cpp",
    "message_pack.cpp",
    "message_pack_rpc.cpp"
]

mpack_dir = "mpack/src/"
mpack_sources = [
    "mpack/mpack-common.c",
    "mpack/mpack-expect.c",
    "mpack/mpack-node.c",
    "mpack/mpack-platform.c",
    "mpack/mpack-reader.c",
    "mpack/mpack-writer.c",
]

mpack_sources = [mpack_dir + file for file in mpack_sources]

addon_sources.append(mpack_sources)
addon_name = "messagepack"
addon_path = "gdextension_build/example/addons/{}".format(addon_name)
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{0}/bin/lib{1}.{2}.{3}.framework/lib{1}.{2}.{3}".format(
            addon_path,
            addon_name,
            env["platform"],
            env["target"]
        ),
        source=addon_sources,
    )
else:
    library = env.SharedLibrary(
        "{0}/bin/lib{1}{2}{3}".format(
            addon_path,
            addon_name,
            env["suffix"],
            env["SHLIBSUFFIX"]
        ),
        source=addon_sources,
    )

Default(library)
